### ISSUE TITLE
Incorrect countdown in both desktop and mobile browser

### ISSUE THREAD

**Issue by achmadk** [thiagozanetti/react-moment-countdown#1]
Excuse me, sir @thiagozanetti . I have used your package in my project. I attached one of the screenshot of my project  
  
![localhost-8080-](https://cloud.githubusercontent.com/assets/8057028/25751712/2295f246-31e0-11e7-9f56-507be8c4bd3f.png)

the countdown above is the result from your package, and the other one is expected result. Comparison between its two countdowns is very different.  

I have updated your package (`dependency` version, `README.md`, `index.jsx`, and `format-date.js` file) that can display better countdown result. You can view the difference in [this link](https://github.com/thiagozanetti/react-moment-countdown/compare/master...achmadk:master)

**Comment by thiagozanetti** [comment]
I apologize the lack of time to work on this component and its docs (we still need some tests too).

Why don't you open a PR so we can discuss it further? There are some practices (use of `const` instead of `let`, `strict` comparison (===) instead of `abstract` one (==), use of curly braces (`{}`) on if statements, etc...) I believe we can apply to improve code even more. 

Thank you @achmadk for your effort. It is a great improvement. I really liked what you did.

**Comment by achmadk** [comment]
I want to hear your feedback before I create PR.  

Maybe we can specify code style between [eslint][eslint link] or [standard][standard link] for next update. I use standard with addtional [babel-eslint][babel-eslint link] parser.  

[eslint link]: https://github.com/eslint/eslint
[standard link]: https://github.com/feross/standard
[babel-eslint link]: https://github.com/babel/babel-eslint

**Comment by thiagozanetti** [comment]
I would rather use `eslint` but `standard` seems to be a good choice too. I liked what you did, even not understanding the purpose of `editTargetFormatMask` clearly. I only endorse the use of the rules that I've already commented, plus the use of trailing commas to avoid the `comma dangling`.
